### PR TITLE
Added tvOS Support 

### PR DESCRIPTION
**Pull request by criszz77**
This PR adds a minimal support for tvOS solving #15 

Run `yarn add react-native-media-console@next` to check it out.

@esegebart Please try this version out as I made some small refactor and my Android TV simulator does not work anymore for some reason :( I will test it too on mobile only on my project.

### CODE REVIEW

**Comment by criszz77** [comment]
@esegebart Let's write here any issues that we can find today with the tvOS support. I am testing it on my project which is a bare React Native project, (without tvOS) all and it seems to be working very good so far.

**Comment by esegebart** [comment]
@criszz77 Yes, I had made the project as you said in the previous discussion with typescript and I got an error. Here are some screenshots, react-native info, and packages.

### React-native info

> System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 1.13 GB / 15.83 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.2, 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Screenshots

#1
image
#2
image

### Packages
```
{
  "name": "TSmediaControls",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@babel/preset-env": "^7.1.6",
    "react": "18.1.0",
    "react-native": "0.70.0",
    "react-native-media-console": "^2.0.0-4",
    "react-native-video": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.69.6",
    "@types/react-native-video": "^5.0.14",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.36.2",
    "@typescript-eslint/parser": "^5.36.2",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.2"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

This was tested on Android TV emulator.

**Comment by criszz77** [comment]
@esegebart It's a bare React Native project, so there's no support for tvOS, only for mobile. 🥺 Should work if you try on a mobile simulator?

**Comment by criszz77** [comment]
@esegebart Sorry for the confusion, but I also changed the issue into a discussion here: https://github.com/criszz77/react-native-media-console/discussions/20

**Comment by esegebart** [comment]
@criszz77 Oh wow, I am dense today. Of course it wouldn't work on tv simulator. :D Forgive me LOL.

**Pull request merged**
